name: Node.js CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x,16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: experiment
        run: |
          cd server
          pwd
      - name: npm install --save-dev jest
        run: npm install --save-dev jest
      - name: tests
        run: npm run